{
  "components": {
    "securitySchemes": {
      "apiKey": {
        "in": "header",
        "name": "X-API-Key",
        "type": "apiKey"
      },
      "basicAuth": {
        "scheme": "basic",
        "type": "http"
      }
    }
  },
  "info": {
    "description": "API con autenticaci\u00f3n b\u00e1sica, API Key y filtrado por IP",
    "title": "API Flask Segura",
    "version": "1.0.0"
  },
  "openapi": "3.0.3",
  "paths": {
    "/api/protegida": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "mensaje": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Acceso autorizado"
          },
          "401": {
            "description": "Credenciales o API Key inv\u00e1lidas"
          },
          "403": {
            "description": "IP no autorizada"
          }
        },
        "security": [
          {
            "basicAuth": []
          },
          {
            "apiKey": []
          }
        ],
        "summary": "Endpoint protegido"
      }
    }
  }
}
