openapi: 3.0.3
info:
  title: API Segura con Flask
  version: 1.0.0
paths:
  /api/protegida:
    get:
      summary: Ruta protegida con autenticación básica, API Key e IP
      security:
        - basicAuth: []
        - apiKey: []
      responses:
        '200':
          description: Acceso autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
        '401':
          description: Credenciales o clave API inválidas
        '403':
          description: IP no autorizada
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
